### ISSUE TITLE
code need replace to msg

### ISSUE THREAD

**Issue by rnyPlanet** [s00d/onlinesim-python-api#1]
https://github.com/s00d/onlinesim-python-api/blob/f8d2e212e81017507565d3dac662480758d2ba12/onlinesimru/GetNumbers.py#L51

**Comment by s00d** [comment]
hello. Added new parameter full_message.

https://github.com/s00d/onlinesim-python-api/blob/cf4217d6c0d300e27fc411f2f57e5588ec2a4718/onlinesimru/GetNumbers.py#L42
