### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by hostegy** [s00d/onlinesim-python-api#13]
can u help me to setup on my cpanel and doamin i cannt setup it

**Comment by hostegy** [comment]
![2022-07-23_083155](https://user-images.githubusercontent.com/109705819/180593574-bd439e57-7ad3-47eb-b5a7-7e7a0c5cbe64.png)
# [#[](url)]([url]([url](url)))

**Comment by hostegy** [comment]
#[](url)

**Comment by s00d** [comment]
hello, we do not set up servers

**Comment by hostegy** [comment]
iam setup php server but i have problem for thats this name 
[~/sms.mcs4.me/onlinesim-php-api-master]# composer run-script test
> vendor/bin/phpunit
Script vendor/bin/phpunit handling the test event returned with error code 255
elhakimk@s1 [~/sms.mcs4.me/onlinesim-php-api-master]# ^C
elhakimk@s1 ~/sms.mcs4.me/onlinesim-php-api-master]#[

- [ ]

**Comment by hostegy** [comment]
i used this 


    # - name: Run test suite
    #   run: composer run-script test
