### ISSUE TITLE
Problem in installing onlinesim package

### ISSUE THREAD

**Issue by its0x4d** [s00d/onlinesim-python-api#17]
I Installed the package and i got this error

![image](https://user-images.githubusercontent.com/58491910/218949309-d5e2a501-8278-49d3-b6cb-1e1b79732757.png)

![image](https://user-images.githubusercontent.com/58491910/218949459-e238510c-4e96-49f9-9348-134ed5cd11be.png)

i think it's not installed perfectly 

i used this cmd for the installation 

`$ pip install onlinesimru --upgrade`

**Comment by s00d** [comment]
fixed. try 2.0.3
