### ISSUE TITLE
Some Questions / Errors

### ISSUE THREAD

**Issue by bralbral** [s00d/onlinesim-python-api#2]
Hello, thank you for api. I have several questions about how it works ;)

`code = driver.numbers().wait_code(tzid=tzid, timeout=60*3)`

if sms-message did not received and timeout was expired will raised unexpected error:

```
File GetNumbers.py line 53. 
 if response['code'] and not not_end and response['code'] != __last_code:
KeyError: 'code'
```

And can you raise custom exception instead of Exception, because it's hard to resolve it?

```
File GetNumbers line 49:

   while True:
            time.sleep(timeout)
            counter += 1
            if counter >= 10:
                raise ('Timeout error')                          <-----THIS
            response = self.stateOne(tzid, 1, False)


```

So through web you can **ban** bad number after some time.

How can i do it using api? 

Thanks!

**Comment by s00d** [comment]
Hello. Added TimeoutException and fix wait_code
try 1.0.8
