### ISSUE TITLE
 GetNumbers.py , close function.

### ISSUE THREAD

**Issue by bralbral** [s00d/onlinesim-python-api#3]
Good day!

Can you implement parameter **"ban"** for function **close**?

```
   GetNumbers.py  line 29
    def close(self, tzid: int):
        return self._get(f'/setOperationOk', {'tzid': tzid})
```

According [documentation](https://onlinesim.ru/docs/api/ru#setoperationok) you can ban number after 5 min  waiting.

Thanks!

**Comment by s00d** [comment]
Hello.
added ban 
https://github.com/s00d/onlinesim-python-api/blob/0553c706386a7f395086307c86bc0de2f083681e/onlinesimru/GetNumbers.py#L32
