### ISSUE TITLE
Issue for Telegram code request.

### ISSUE THREAD

**Issue by captainluzik** [s00d/onlinesim-python-api#5]
In the example to get the code, you specified the following:
# multiple driver using
from onlinesimru import Driver

def main():
    driver = Driver('YOUR_TOKEN')

    tzid = driver.numbers().get('service')
    print(tzid)
    code = driver.numbers().wait_code(tzid)
    print(code)

main()
When receiving SMS from Telegram, this method displays ID messages.
[13464390577]` where full SMS is `[16042601337] Telegram code 98454
I propose to add an example to receive SMS from a telegram.
from onlinesimru import Driver
def main():
    driver = Driver('YOUR_TOKEN')
    tzid = driver.numbers().get('service')
    print(tzid)
    code = driver.numbers().wait_code(tzid=tzid, full_message=True)
    code = code.split('Telegram code ')
    print(code[1])
main()

Thanks

**Comment by s00d** [comment]
please correct the message.  
And need a number or user id. You can send them via the support chat on the site
