### ISSUE TITLE
General question regarding getFreeMessageList API call

### ISSUE THREAD

**Issue by thomasgruebl** [s00d/onlinesim-python-api#7]
Why is the API call https://onlinesim.ru/api/getFreeMessageList?cpage=1&phone=+46700000000  not working and returning an empty data field? Note: I've replaced the phone number with a working phone number from onlinesim.ru.

Still, the data fields are always empty. This should be a functioning API call according to the documentation (https://onlinesim.ru/docs/api/en/free/getFreeMessageList)

**Comment by s00d** [comment]
hello. api was changed
https://onlinesim.ru/api/getFreeMessageList?cpage=1&country=46&phone=700000000
